### ISSUE TITLE
Gradients only available up to Rn?

### ISSUE THREAD

**Issue by rafaelpap** [dftd4/dftd4#111]
**Describe the bug**
When asking for gradients for atoms beyond Rn the output is NaN.
I wonder if it is a bug.

**To Reproduce**
Steps to reproduce the behaviour:

1. happens with input (include input files): rah2ob.xyz has gradients as NaN
2. start `dftd4` with (all the options here): dftd4 --func tpssh -c 2 --grad kk rah2ob.xyz

 
3. output showing the error: rah2ob.out

Please provide all input and output file such that we confirm your report.
[ra_and_rn.zip](https://github.com/dftd4/dftd4/files/6746373/ra_and_rn.zip)
**Expected behaviour**
I expected a result similar to the one in rnh2ob.out

**Additional context**
If I run dftd4  rah2ob.xyz there is no data for Ra in the "Atomic reference systems (in atomic units):" table.

**Comment by awvwgk** [comment]
The reference polarizibility data is only available up to Rn (but we still have some data on the far end starting from Cn again). I agree that it would be better to gracefully exit in case we encounter an unsupported element instead of just running the calculation.

There have also been discussions whether we want to fill the gap between Rn and Cn by calculating the reference polarizibility data for the remaining elements. But this hasn't been completed yet.

**Comment by rafaelpap** [comment]
Thanks.
