### ISSUE TITLE
dftd4 build error when compiled with intel 21.4.0

### ISSUE THREAD

**Issue by hpcnpatel** [dftd4/dftd4#161]
**Describe the bug**
Installation dftd4 with intel-oneapi-compiler/21.4.0 throws build error,

````
==> Installing dftd4-3.4.0-6lq6nlvn3tnryivoaehspd77hi4jik3n
==> No binary for dftd4-3.4.0-6lq6nlvn3tnryivoaehspd77hi4jik3n found: installing from source
==> Using cached archive: ~/spack/cache/_source-cache/archive/24/24fcb225cdd5c292ac26f7d3204ee3c4024174adb5272eeda9ae7bc57113ec8d.tar.xz
==> No patches needed for dftd4
==> dftd4: Executing phase: 'meson'
==> Error: ProcessError: Command exited with status 1:
    'meson' '~/haswell/spack-stage-dftd4-3.4.0-6lq6nlvn3tnryivoaehspd77hi4jik3n/spack-src' '--prefix=~/haswell/dftd4/3.4.0-intel-6lq6nlv' '--libdir=~/haswell/dftd4/3.4.0-intel-6lq6nlv/lib' '-Dbuildtype=debugoptimized' '-Dstrip=false' '-Ddefault_library=shared' '-Dlapack=mkl' '-Dopenmp=true' '-Dpython=false'

1 error found in build log:
     21    Host machine cpu: x86_64
     22    C compiler for the host machine: icc (intel 2021.4.0 "icc (ICC) 2021.4.0 20210910")
     23    C linker for the host machine: icc ld.bfd 2.37.20211103-7
     24    Run-time dependency OpenMP found: YES 5.0-revision1
     25    Library mkl_intel_lp64 found: YES
     26    
  >> 27    ../config/meson.build:58:6: ERROR: Fortran shared or static library 'mkl_intel_thread' not found
     28    
     29    A full log can be found at ~/haswell/spack-stage-dftd4-3.4.0-6lq6nlvn3tnryivoaehspd77hi4jik3n/spack-src/spack-build/meson-logs/meson-log.t
           xt

````

**To Reproduce**
spack install dftd4%intel@21.4.0

**Additional context**
Probably a solution would be to add -Dfortran_link_args=-qopenmp when compiled with intel@21.4.0

I am not sure. I just wanted your feedback. What would be the cause of this build error? I have adopted the spack package locally, adding this flag. What would be your recommendations to fix the build error and spack package?

**Comment by awvwgk** [comment]
It's still an option issue (see https://github.com/grimme-lab/xtb/issues/402), however I haven't found a proper fix yet.

If you check the meson log you will find that some symbols related to OpenMP are not resolved and therefore the `find_library` command is failing, the hacky fix is to exploit that `-Dfortran_link_args` injects the additional arguments globally, even into the library finder and therefore allows to find `mkl_intel_thread`. Not sure whether it is intended for `find_library` to be affected by link arguments from the command line since `find_library` normally doesn't take any additional arguments or hints.

I'm still looking forward to see support for MKL linking in upstream meson at some point https://github.com/mesonbuild/meson/issues/2835. An alternative is to choose the `mkl-rt` option to link against the real-time version of MKL, which is usually preferable if you have to dlopen `libdftd4.so` later, *e.g.* from the Python bindings.
