### ISSUE TITLE
wb97x s8 parameter is negative-potentially causing issues?

### ISSUE THREAD

**Issue by reinhacr** [dftd4/dftd4#188]
Hi there,

I responded to a closed issue but I realized that may not get seen or addressed, so opening it as a new issue. I am seeing some weird behavior with the default parameters of wb97x, which I believe is related to the negative s8 parameter as the poster above mentions. When changing these parameters to the new ones published with the HS13L paper SI, the values are much more consistent and reasonable. This behavior is observed in both a large nanocage system which is highly charged, which I didn't trust as much, so I verified that it also occurs in the simple benzene dimer system. Will this be an issue with other functionals with negative s8 parameters? I can provide more files if needed, but I'm sure this is relatively easy to test as well. I built dftd4 in a clean conda environment a few days ago, and otherwise it seems to work well. 

Please see thread referenced at the bottom of this for the original response on the closed issue.

>       Hi, I did some more tests as I wanted to be sure it wasn't just my system, as its large and charged as discussed above, so `I built a simple benzene dimer. The following is an excerpt of my spreadsheet. To be clear, I did not optimize the benzene dimer with DFT first or anything, just built in Avogadro, did a quick geometry clean (UFF), which resulted in a visually good geometry of what I wanted, and proceeded. I then used the standalone dftd4 package for the d4 entries, and the d3 entries were with the standalone s-dftd3 package. I copied the full values from the program into the spreadsheet, but have the full entries displayed in number as opposed to scientific mode, but values of 0.00 are not such. I did not pass any other options besides explicitly declaring the charge to be zero for the dftd4 and specifying the functional, besides in the case of the HS13L reading in the new parameters with the addition of the "--param 1.0, 0.4485, 0.3306, 4.2790" flag to the command. The output I verified that these were read. Granted, the functionals are different from each other as expected but all other d3 to d4 differences are relatively small and consistent, besides the wb97x which is 2 kcal/mol different. I could have posted a new issue, but I figure I'd leave it here and just tag the relevant parties. @awvwgk `

BENZENE DIMER | MONOMER 1 | MONOMER 2 | DIMER | dE_disp_binding (dimer-(monomer+monomer) converted to kcal/mol
-- | -- | -- | -- | --
wb97x zero dampening-d3 | 0.00 | 0.00 | -0.01 | -3.48 |  
wb97x d3 | -0.02 | -0.02 | -0.05 | -3.74 |  
b3lyp d3 | -0.02 | -0.02 | -0.05 | -5.32 |  
b3lyp d4 | -0.02 | -0.02 | -0.04 | -5.57 |  
wb97x d4 negative s8 default params | 0.00 | 0.00 | 0.00 | -1.21 |  
wb97x d4 params published in HS13L SI and wb97x-3c paper | -0.02 | -0.02 | -0.04 | -3.65 |  

_Originally posted by @reinhacr in https://github.com/dftd4/dftd4/issues/16#issuecomment-1397787964_

**Comment by marvinfriede** [comment]
Hi,

as mentioned in the closed issue, a negative $s_8$ parameter is unphysical because it implies that the dispersion contains a repulsive part. Hence, if you only look at the dispersion energy, it is not surprising that it is larger (less negative) compared to other functionals with typical $s_8$ values. I would argue that a negative $s_8$ tries to absorb shortcomings of the density functional. In my experience, the parameter fit produces a negative $s_8$ if the functional is already too attractive, which then interferes with the always attractive dispersion correction.
And as far as I know, the wB97X functional is not known to be overly attractive. Therefore, I recommend the D4 parameters for wB97X from the wB97X-3c paper, which are also fitted on a larger and more diverse set of molecules. They have also been shown to be superior to the D4 parameters from [here](https://onlinelibrary.wiley.com/doi/10.1002/jcc.26411).
I am currently working on a project related to D4 parameter fitting, which gives some further insight. I will post a link when it is published.


Best,
Marvin

**Comment by reinhacr** [comment]
Perfect, that makes complete sense. I guess I should clarify when I wrote the above table, I meant wb97x, not wb97xd so I edited that, but sounds good! I will use the parameters with the correct function appropriately!
