### ISSUE TITLE
Is parallelization possible?

### ISSUE THREAD

**Issue by atom-moyer** [dftd4/dftd4#20]
Hi again,

I am using the DFTD4 in conjunction with the AIMNet neural network model (https://github.com/aiqm/aimnet) which is trained on 20MM+ wB97x/def2-TZVPP off-equilibrium calculations. 

I have found that this dispersion correction is a nice correction for non-covalent interactions. However, compared to the performance of the neural network on GPUs I am finding that the single thread dispersion correction runs in approximately the same time as the neural network for systems with ~15 heavy atoms. Even worse, when I run on systems of ~200 heavy atoms, I am finding that the dispersion correction takes 10x longer to run than the neural network!

Is there any way to speed up the dispersion correction? I have 5 cpus per gpu so I could use multithreading if that is available. I do not see anywhere to turn on parallelization via the python interface.

Thanks,
Adam

**Comment by atom-moyer** [comment]
Also, just double checking that I am not doing anything crazy.

For 2 residue poly-ALA:
The D4 correction is calculating 80 per second. 
The neural network is calculating 180 per second.

For 12 residue poly-ALA:
The D4 correction is calculating 8 per second. 
The neural network is calculating 80 per second.

Is that performance that you would expect for the D4 correction?
Would you recommend using a different dispersion correction if speed is necessary to me?

**Comment by awvwgk** [comment]
Thanks for checking.

#### Technical Details

Indeed we are currently only offering openMP parallelisation in `dftd4`, so we have neither MPI nor GPU support available right now, which makes your neural network clearly superior if you go massively parallel. I should stress that `dftd4` implements a method meant to be used together with DFT.

We can definitely speed up `dftd4` quite a lot (sparse solvers, MPI, maybe GPU support), but so far this what not in-scope for a dispersion correction targeting DFT, since you hardly notice the `dftd4` run there.

#### What to do?

Now since you are designing a low-cost method, there are several things we can do, from a methodological point. `dftd4` is build quite modular, so we can start throwing away terms, which will increase the speed by sacrificing some accuracy (so the usual trade-off when designing low-cost methods). So you can try to

- reduce the cutoff radii (currently only possible in the source code)
- disable the Axilrod-Teller-Muto three-body correction
- disable the charge calculation (yields effectively D3, if you do a few more changes)

*I should mention that there is no point in doing this when combining D4 with DFT* (just as a disclaimer for future readers).

We also have very efficient implementations of D3 available for using it in the force field context, feel free to contact my boss or me if you are interested in using them.

**Comment by atom-moyer** [comment]
Thanks a bunch for getting back to me.

I would be able to utilize the openMP support because my 5 cpus are on one node. Is that connected through the python interface? It looks like it was meant to be supported, but to my understanding of the code, it does not actually get passed through the python-fortran bindings.

**Comment by awvwgk** [comment]
Of course, but you have to compile with openMP support and set the respective environment variables (if you use MKL as backend, set the threads there as well!). Right now you cannot set it in Python via the API, but you can set it by environment variables.

**Comment by awvwgk** [comment]
@atom-moyer is this still an issue?

**Comment by awvwgk** [comment]
Closing this issue as stale.

The reference DFT-D4 implementation provides a shared memory parallelisation for CPUs. Investing in GPU parallelisation currently seems unfeasible for this project due to the limited toolchains available for this purpose. Revisiting different implementations using MPI (like the D4 variant in DFTB+) or OpenACC (like the D4 variant in `xtb`) could be done as part of this project in the future or in a separate project as necessary.
