### ISSUE TITLE
DLL IMPORT/EXPORT is not supported on this platform

### ISSUE THREAD

**Issue by siamak-attarian** [dftd4/dftd4#205]
Hello, 

When I try to compile dftd4 (using either meson or cmake) I get multiple warnings such as :

 /home/sattarian/dftd4-main/src/dftd4/api.f90(682): remark #7841: DLL IMPORT/EXPORT is not supported on this platform.   [DLLEXPORT] !DEC$ ATTRIBUTES DLLEXPORT :: get_properties_api

for multiple files.

I tired both oneapi2023.0 and oneapi2023.1 and I get the same warning for both. With oneapi2023.0 when trying the test suite, the "api" test fails, but with oneapi2023.1 all the tests are passed. When trying to compile vasp with dftd4 I get a series of errors  like:
/home/sattarian/dftd4-main/src/dftd4/damping/rational.f90:147: undefined reference to `__kmpc_global_thread_num'

There are too many of these warning/errors. I can copy paste the errors if it helps.

Any idea what's happening?

Thanks,
Siamak

**Comment by logzzzzz** [comment]
This may be a version issue, I get the same error compiling DFTD4-3.5 with intel2019, but compiling DFTD4-3.4 can be compiled without any problem.

**Comment by TyBalduf** [comment]
@siamak-attarian Do you find any compiler messages starting with "error", "fail", or "warn"? The DLL IMPORT/EXPORT messages are a red-herring, as these are just "remarks" rather than warnings/errors, so they can be safely ignored. If the test suite is passing with oneapi2023.1, that would seem to suggest it built successfully.

Is there a failure message with the api test failure for oneapi2023.0?

Even if it is long, it would be good to include the whole compilation output as a code block.

The failure to build with VASP should maybe be a separate issue. Just as a sanity check, are you sure you followed all special instructions for building VASP with D4 from the README?
