### ISSUE TITLE
Do vasp implementations of DFT-D3 and D4 contain the ATM three-body term? 

### ISSUE THREAD

**Issue by jjhjm17** [dftd4/dftd4#222]
**Is your feature request related to a problem? Please describe.**

This is more like a question, not a feature request.

First we thank the developers for this very fast, accurate, and versatile van der Waals correction, which enabled us to calculate the energy of solid SiO2 now.

The three body term (ATM) is turned off as a default for a periodic system in the DFT-D3 package, as described in its manual.

Is the ATM three body term considered in the vasp implementation of DFT-D4? (We could not find a manual for DFT-D4.) If it is ignored, how can we add it?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context** (edited)

**Comment by marvinfriede** [comment]
Generally, the ATM term is always turned on for DFT-D4. In the [paper](https://doi.org/10.1063/1.5090222) (section II E), it says, "The DFT-D4 default model always includes an ATM term [...].". Additionally, the ATM term is scaled by the `s9` parameter, which defaults to `1.0`. Only for double hybrid functionals or tailored functionals (e.g., r2SCAN-3c) different values are used, but they are still non-zero.

Since I am not familiar with VASP, I do not know if any specific flags in VASP itself are required. But from the above reasoning and also the [code](https://github.com/dftd4/dftd4/blob/0627ec8939b089c00aa0e4005c401e603806adf6/src/dftd4/compat.f90#L137) in the VASP compatibility layer of D4, ATM should be enabled by default.

**Comment by jjhjm17** [comment]
Dear Marvin Friede,

We appreciate your clear explanation on this matter and also the reference to the source code!
