### ISSUE TITLE
D4 dispersion with B97D functional

### ISSUE THREAD

**Issue by dumalenovshan** [dftd4/dftd4#243]
I tried calculating D4 energy with B97D functional:

dftd4 --func b97d coords.xyz

However, an error occurs, saying that b97d is not a supported functional. Is there another keyword for B97D? In the list of parameters it is written as "b97d".

Also, CAM-B3LYP has to be written "cam-b3lyp" in order to work properly, in spite of being written as "camb3lyp" in the parameters list.

**Comment by marvinfriede** [comment]
For "b97d", the name is missing in the code. This is a bug. However, this is already fixed in the latest commit. If you cannot compile the code from source, you can specify the B97D parameters directly.

```sh
dftd4 --param 1.0000 1.69460052 0.28904684 4.13407323 coords.xyz
```

Both names for CAM-B3LYP are also available in the latest commit, but not yet in version 3.6.0.
