### ISSUE TITLE
Print Edisp to machine precision

### ISSUE THREAD

**Issue by RomitChakraborty** [dftd4/dftd4#37]
Would be nice to have a command-line option that prints Edisp to machine precision.

Based on a cursory scan of the source, I wasn't able to tweak it to format Edisp output to display at machine precision -- 15-16 places of decimal in scientific format. How does one go about doing that?
Maybe having a command-line option to do so would be something to consider?

**Comment by awvwgk** [comment]
The format is specified here:

https://github.com/dftd4/dftd4/blob/37e171189af2126bf94caff5449b941f737579b3/source/program_dftd.f90#L185-L187

Use `es25.16` or `g0` instead of `f12.8` to print with full precision.

I could also add a machine readable printout like JSON with the full precision for this.

**Comment by RomitChakraborty** [comment]
This works! Thanks Sebastian.
A JSON file would be super helpful also.


*Romit Chakraborty*
*Postdoc*

*Martin Head-Gordon Group*

*University of California, Berkeley, and, *
*Lawrence Berkeley National Lab *
